### ISSUE TITLE
post-navigation below each post in index-loop

### ISSUE THREAD

**Issue by Audiovoyeur** [joshuaiz/template#3]
Much respect josh. Love your fork of bones. 

I found that  the post page navigation appears below each post snippit in the blog view if wordpress is set to "show summery"

I suggest we move <?php get_template_part( 'templates/post-navigation'); ?> from the templates/index-loop.php should might need to actually be in the index.php - 

This also applies to the archives.

I am new to this - apologies if this is out of place.

**Comment by joshuaiz** [comment]
No worries...let me take a look and I'll hit you back. Thanks for this.

**Comment by joshuaiz** [comment]
This isn't necessary as index.php already calls the loop template part which already calls the template_page_navi() function. The 'full text' vs. 'summary' really only applies to RSS feeds.

I'm going to close this but if you can provide an example of what you mean that isn't covered already, I can reopen.

**Comment by Audiovoyeur** [comment]
Cool. Thanks Josh. Loving Template!
